In [6]:
import numpy as np


## __1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

In [3]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
x @ y

33

In [4]:
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
x @ y

-23

## __2.__ Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.

In [5]:
x = np.array([4,2,4])
y = np.array([12,3,4])

In [6]:
np.linalg.norm(x), np.linalg.norm(y)

(6.0, 13.0)

In [11]:
np.degrees(np.arccos((x @ y) / (np.linalg.norm(x) * np.linalg.norm(y))))

26.176952171666542

## __3.__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?

Нет и нет)

## __4.__ Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>
г) $(1,0,0),(0,1,0),(0,0,1)?$ 

а) нет <br>
б) ортогональный но не нормированный <br>
в) нет <br>
г) да

## __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;                          
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;                         
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;                           
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.    


   а)$AB$ нельзя, $BA$ нельзя
    
   б)$AB$ можно 2 x 3, $BA$ нельзя
    
   в)$AB$ можно 8 x 8, $BA$ можно 3 x 3
    
   г)$AB$ можно 4 x 4, $BA$ можно 4 x 4

## __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [13]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [17]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [15]:
A @ B

array([[  4, -11],
       [ 12,  -3]])

## __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [7]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

## __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [24]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [27]:
A @ A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [28]:
A.T @ A

array([[45,  0],
       [ 0, 14]])

##  __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [45]:
def dot(a, b):
    
    def sum_(firs, sec):
        
        if len(firs) == len(sec):
            sum_q = 0
            for i in range(len(firs)):
                sum_q += firs[i] * sec[i]
        
        return sum_q
        
    dot_ = np.zeros(shape=(a.shape[0], b.shape[1]))
    for row in range(dot_.shape[0]):
        for column in range(dot_.shape[1]):
            dot_[row][column] = sum_(a[row], b[:,column])
    
    return dot_

In [46]:
dot(A, A.T)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

In [44]:
dot(A.T, A)

array([[45.,  0.],
       [ 0., 14.]])

## __1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$



а) 1

б)

In [50]:
A = np.array([[4, 1, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(A)

180.0

в)

In [51]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

-9.51619735392994e-16

0

## __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) 16

б) 4

в) 4 * 2^размерность матрицы

## __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [12]:
 A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

In [14]:
np.linalg.det(A)

0.0

## __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [10]:
 A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

In [13]:
np.linalg.matrix_rank(A)

2

In [14]:
A = np.array([[0, 0, 2, 3],[0, 0, 2, 2],[0, 0, 4, 3],[2, 3, 5, 6]])

In [15]:
np.linalg.matrix_rank(A)

3